
###############################################################
# Application
###############################################################

spring.application.name=user-access-api

server.port=9997


###############################################################
# Keycloak
###############################################################

keycloak.server-url=http://localhost:9001

keycloak.realm=platform

keycloak.client-id=user-access-api-client

keycloak.client-secret=Y3bN3yyuw6zO0uYZ6leJQeKUtATSONAf

###############################################################
# Keycloak Admin
###############################################################

#keycloak.admin.username=admin
#keycloak.admin.password=admin123


###############################################################
# Logging
###############################################################

logging.level.root=INFO

logging.level.com.hussain.useraccess=DEBUG


